// same logic and signature as emitSchemaDefinitionFile
// but only logs it to the console for Cloudflare Workers compatibility.

import { type GraphQLSchema, lexicographicSortSchema, printSchema } from "graphql";
import { type PrintSchemaOptions, defaultPrintSchemaOptions } from "@/utils/printSchemaOptions";

const generatedSchemaWarning = /* graphql */ `\
# -----------------------------------------------
# !!! THIS FILE WAS GENERATED BY TYPE-GRAPHQL !!!
# !!!   DO NOT MODIFY THIS FILE BY YOURSELF   !!!
# -----------------------------------------------

`;

function getSchemaFileContent(schema: GraphQLSchema, options: PrintSchemaOptions) {
  const schemaToEmit = options.sortedSchema ? lexicographicSortSchema(schema) : schema;
  return generatedSchemaWarning + printSchema(schemaToEmit);
}

export function emitSchemaDefinitionFileSync(
  _schemaFilePath: string,
  schema: GraphQLSchema,
  options: PrintSchemaOptions = defaultPrintSchemaOptions,
) {
  const schemaFileContent = getSchemaFileContent(schema, options);
  console.log(schemaFileContent);
}

export async function emitSchemaDefinitionFile(
  _schemaFilePath: string,
  schema: GraphQLSchema,
  options: PrintSchemaOptions = defaultPrintSchemaOptions,
) {
  const schemaFileContent = getSchemaFileContent(schema, options);
  console.log(schemaFileContent);
}
